#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# or the 9th iteration, displays Best School and then Hi on a new line.

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counter++ ))
done
